config/routes.rb
Rails.application.routes.draw do
  get 'about/feedback'
  post 'about/feedback'
  get 'about', to: 'about#index'
  get 'about/feeds'
  get 'about/help'
  get 'about/changelog'

  root 'index#index'

  # Catch all old pgo feeds
  get 'feed(/*stuff)', to: 'about#legacy', defaults: { format: 'atom' }

  resources :categories, only: %i[index show search]

  resources :packages, only: [:index, :show, :search], constraints: { id: /[^.]*/ } do
    collection do
      get 'search'
      get 'suggest'
      get 'resolve'

      get 'added'
      get 'updated'
      get 'stable'
      get 'keyworded'
    end

    member do
      get 'changelog'
    end
  end

  resources :useflags do
    collection do
      get 'popular'
      get 'search'
      get 'suggest'
    end
  end

  resources :arches do
    member do
      get 'stable'
      get 'keyworded'
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/useflag.rb
require 'virtus'

class Useflag
  include Virtus.model
  include Kkuleomi::Store::Model

  # index_name "useflags-#{Rails.env}"

  attribute :name,              String, mapping: { type: 'keyword' }
  attribute :description,       String, mapping: { type: 'text' }
  attribute :atom,              String, mapping: { type: 'keyword' }
  attribute :scope,             String, mapping: { type: 'keyword' }
  attribute :use_expand_prefix, String, mapping: { type: 'keyword' }

  def all_fields
    [:name, :description, :atom, :scope, :use_expand_prefix]
  end

  def to_param
    name
  end

  def strip_use_expand
    name.gsub(use_expand_prefix + '_', '')
  end

  class << self
    # Retrieves all flags sorted by their state
    def get_flags(name)
      result = { local: {}, global: [], use_expand: [] }

      find_all_by(:name, name).each do |flag|
        case flag.scope
        when 'local'
          result[:local][flag.atom] = flag
        when 'global'
          result[:global] << flag
        when 'use_expand'
          result[:use_expand] << flag
        end
      end

      result
    end

    def suggest(q)
      results = Useflag.search(
        size: 20,
        query: { match_phrase_prefix: { name: q } }
      )

      processed_results = {}
      results.each do |result|
        if processed_results.key? result.name
          processed_results[result.name] = {
            name: result.name,
            description: '(multiple definitions)',
            scope: 'multi'
          }
        else
          processed_results[result.name] = result
        end
      end

      processed_results.values.sort { |a, b| a[:name].length <=> b[:name].length }
    end

    # Loads the local USE flags for a given package in a name -> model hash
    #
    # @param [String] atom Package to find flags for
    # @return [Hash]
    def local_for(atom)
      map_by_name find_all_by(:atom, atom)
    end

    # Maps the global USE flags in the index by their name
    # This is expensive!
    #
    def global
      map_by_name find_all_by(:scope, 'global')
    end

    # Maps the USE_EXPAND variables in the index by their name
    #
    def use_expand
      map_by_name find_all_by(:scope, 'use_expand')
    end

    private

    def map_by_name(collection)
      map = {}

      collection.each do |item|
        map[item.name] = item
      end

      map
    end
  end
end

app/controllers/useflags_controller.rb
class UseflagsController < ApplicationController
  before_action :set_nav

  def index
    @title = t :use_flags
  end

  def show
    @useflags = Useflag.get_flags(params[:id])

    if @useflags.empty? || (@useflags[:use_expand].empty? && @useflags[:local].empty? && @useflags[:global].empty?)
      fail ActionController::RoutingError, 'No such useflag'
    end

    @packages = Package.find_atoms_by_useflag(params[:id])
    @title = '%s – %s' % [params[:id], t(:use_flags)]

    unless @useflags[:use_expand].empty?
      @useflag = @useflags[:use_expand].first
      @use_expand_flags = Useflag.find_all_by(:use_expand_prefix, @useflag.use_expand_prefix)
      @use_expand_flag_name = @useflag.use_expand_prefix.upcase

      render template: 'useflags/show_use_expand'
      return
    else
      render template: 'useflags/show'
    end
  end

  def search
    # TODO: Different search?
    @flags = Useflag.suggest(params[:q])
  end

  def suggest
    @flags = Useflag.suggest(params[:q])
  end

  def popular
    @popular_useflags = Rails.cache.fetch('popular_useflags', expires_in: 24.hours) do
      Version.get_popular_useflags(100)
    end
  end

  private

  def set_nav
    @nav = :use
  end
end

app/helpers/useflags_helper.rb
module UseflagsHelper
  def annotate_useflag_description(str)
    sanitize(str.gsub(/<pkg>([^<]+)<\/pkg>/) { pkg=$~[1] ; link_to(pkg, slf(package_path(pkg))) }, tags: ['a'], attributes: ['href'])
  end
end

app/views/useflags/_useflag_header.html.erb
<ol class="breadcrumb">
  <li><a href="/"><%= t :home %></a></li>
  <li><%= link_to t(:use_flags), useflags_path %></li>
  <li class="active"><%= params[:id] %></li>
</ol>

app/views/useflags/_useflag_result_row.html.erb
<a class="list-group-item" href="<%= slf useflag_path useflag[:name] %>">
  <h3 class="kk-search-result-header"><%= useflag[:name] %></h3>
  <%= useflag[:description] %>
</a>

app/views/useflags/index.html.erb
<ol class="breadcrumb">
  <li><a href="/"><%= t :home %></a></li>
  <li class="active"><%= t :use_flags %></li>
</ol>

<h1><%= t :use_flags %></h1>

<div class="alert alert-info">
  Looking for the full USE flag index?
  You can find it on our <a href="https://www.gentoo.org/support/use-flags/" class="alert-link">main website</a>.
</div>

<form action="<%= search_useflags_path %>" method="get" class="useflag-search">
  <div class="typeahead-container">
    <div class="typeahead-field">
      <span class="typeahead-query">
        <input id="q" name="q" type="search" autocomplete="off" placeholder="Find USE flags">
      </span>
      <span class="typeahead-button">
        <button type="submit">
          <span class="typeahead-search-icon"></span>
        </button>
      </span>
    </div>
  </div>
</form>

<br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Most widely used USE flags</h3>
  </div>
  <noscript>
  <div class="panel-body kk-panel-content-sorry">
    This feature requires JavaScript to work.
  </div>
  </noscript>
  <div class="panel-body kk-useflag-bubble-container" id="bubble-placeholder" style="display: none;">
  </div>
</div>

<%= javascript_include_tag 'useflags/typeahead.js' %>
<%= javascript_include_tag 'd3.min.js' %>
<%= javascript_include_tag 'useflags/render-bubbles.js' %>

app/views/useflags/search.html.erb
<ol class="breadcrumb">
  <li><a href="/"><%= t :home %></a></li>
  <li><%= link_to t(:use_flags), useflags_path %></li>
  <li class="active">Search</li>
</ol>

<h1>USE Flag Search Results <small>for <%= params[:q] %></small></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    Results
  </div>
  <div class="list-group">
    <%= render partial: 'useflag_result_row', collection: @flags, as: 'useflag' %>
  </div>
</div>

app/views/useflags/show.html.erb
<%= render partial: 'useflag_header' %>

<div class="row">
  <div class="col-md-4">
    <h1 class="stick-top">
      <span class="fa fa-fw fa-sliders"></span>
      <%= params[:id] %>
    </h1>
  </div>
  <div class="col-md-8">
    <% unless @useflags[:global].empty? %>
      <div class="kk-useflag-group"><%= t :global_use_flag %></div>
      <p class="lead" style="margin: 0;">
          <%= @useflags[:global].first.description %>
      </p>
    <% else %>
      <div class="kk-useflag-group"><%= t :local_use_flag %></div>
    <% end %>
  </div>
</div>

<hr>

<% unless @useflags[:local].empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= t :local_use_package_list, flag: params[:id] %></h3>
    </div>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <th><%= t :package %></th>
          <th><%= t :flag_description, flag: params[:id] %></th>
        </thead>
        <tbody>
          <% @useflags[:local].keys.sort.each do |package| %>
          <tr>
            <th class="kk-nobreak-cell"><%= link_to package, slf(package_path(package)) %></th>
            <td><%= annotate_useflag_description @useflags[:local][package].description %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<% unless @useflags[:global].empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= t :providing_packages_list, flag: params[:id], count: @packages.count %></h3>
    </div>
    <div class="panel-body">
      <ul class="kk-col-list kk-3col-list kk-useflag-listing">
      <% @packages.each do |package| %>
        <li><%= link_to_package package['key'] %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/useflags/show_use_expand.html.erb
<%= render partial: 'useflag_header' %>

<div class="row">
  <div class="col-md-4">
    <h1 class="stick-top">
      <span class="fa fa-fw fa-sliders"></span>
      <%= @useflag.strip_use_expand %>
    </h1>
  </div>
  <div class="col-md-8">
    <div class="kk-useflag-group"><%= t :named_use_expand_flag, name: @use_expand_flag_name %></div>
    <p class="lead" style="margin: 0;">
      <%= @useflags[:use_expand].first.description %>
    </p>
  </div>
</div>

<hr>

<% unless @use_expand_flags.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= t :other_use_expand_list, flag: @use_expand_flag_name %></h3>
    </div>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <th><%= t :use_flag %></th>
          <th><%= t :description %></th>
        </thead>
        <tbody>
          <% @use_expand_flags.each do |flag| %>
          <tr>
            <th class="kk-nobreak-cell"><%= link_to flag.name, slf(useflag_path(flag.name)) %></th>
            <td><%= flag.description %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<% unless @packages.empty? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= t :providing_packages_list, flag: params[:id], count: @packages.count %></h3>
    </div>
    <div class="panel-body">
      <ul class="kk-3col-list kk-useflag-listing">
      <% @packages.each do |package| %>
        <li><%= link_to_package package['key'] %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>