config/routes.rb
Rails.application.routes.draw do
  get 'about/feedback'
  post 'about/feedback'
  get 'about', to: 'about#index'
  get 'about/feeds'
  get 'about/help'
  get 'about/changelog'

  root 'index#index'

  # Catch all old pgo feeds
  get 'feed(/*stuff)', to: 'about#legacy', defaults: { format: 'atom' }

  resources :categories, only: %i[index show search]

  resources :packages, only: [:index, :show, :search], constraints: { id: /[^.]*/ } do
    collection do
      get 'search'
      get 'suggest'
      get 'resolve'

      get 'added'
      get 'updated'
      get 'stable'
      get 'keyworded'
    end

    member do
      get 'changelog'
    end
  end

  resources :useflags do
    collection do
      get 'popular'
      get 'search'
      get 'suggest'
    end
  end

  resources :arches do
    member do
      get 'stable'
      get 'keyworded'
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/category.rb
require 'virtus'

class Category
  include Virtus.model
  include Kkuleomi::Store::Model
  
  # index_name "categories-#{Rails.env}"

  attribute :name,          String, mapping: { type: 'keyword' }
  attribute :description,   String, mapping: { type: 'text' }
  attribute :metadata_hash, String, mapping: { type: 'text' }

  # Determines if the document model needs an update from the repository model
  #
  # @param [Portage::Repository::Category] category_model
  def needs_import?(category_model)
    metadata_hash != category_model.metadata_hash
  end

  # Populates values from a repository category model
  #
  # @param [Portage::Repository::Category] category_model Input category model
  def import(category_model)
    self.name = category_model.name
    self.description = category_model.description
    self.metadata_hash = category_model.metadata_hash
  end

  # Populates values from a repository category model and saves
  #
  # @param [Portage::Repository::Category] category_model Input category model
  def import!(category_model)
    import(category_model)
    save
  end

  # Returns the URL parameter for referencing this package (Rails internal stuff)
  def to_param
    name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :set_nav

  def index
    @categories = Category.all_sorted_by(:name, :asc)
  end

  def show
    @packages = Rails.cache.fetch("category/#{@category.name}/packages",
                                  expires_in: 10.minutes) do
      Package.find_all_by(:category,
                          @category.name,
                          sort: { name_sort: { order: 'asc' } }).map do |pkg|
        pkg.to_os(:name, :atom, :description)
      end
    end

    @description = t(:desc_categories_show,
                     category: @category.name,
                     description: @category.description)
  end

  private

  def set_category
    @category = Category.find_by(:name, params[:id])
    fail ActionController::RoutingError, 'No such category' unless @category

    @title = @category.name
  end

  def set_nav
    @nav = :packages
  end
end

app/views/categories/_category_header.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to t(:packages), categories_path %></li>
  <li class="active"><%= category.name %></li>
</ol>

<div class="row">
  <div class="col-md-4">
    <h1 class="stick-top">
      <span class="fa fa-fw fa-cubes"></span>
      <%= category.name %>
    </h1>
  </div>
  <div class="col-md-8">
    <p class="lead" style="margin: 0;">
      <%= category.description %>
    </p>
  </div>
</div>

<hr>

app/views/categories/_package_line.html.erb
<tr>
  <th class="kk-nobreak-cell"><%= link_to package.name, slf(package_path(package.atom)) %></th>
  <td><%= package.description %></td>
</tr>

app/views/categories/index.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= t :packages %></li>
</ol>

<h1><%= t :packages %></h1>

<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t :browse_categories %></h3>
      </div>
      <div class="panel-body">
        <ul class="kk-col-list kk-4col-list kk-category-listing">
        <%- prev_letter = 'z' -%>
        <% @categories.each do |category| %>
          <%- unless category.name[0].upcase == prev_letter ; prev_letter = category.name[0].upcase -%>
          <li class="kk-col-list-header"><span class="kk-group-header"><%= prev_letter %></span></li>
          <%- end -%>
          <li><%= link_to_category category %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t :update_feeds %></h3>
      </div>
      <div class="list-group">
        <a href="<%= added_packages_path %>" class="list-group-item">
          <span class="fa fa-fw fa-history"></span>
          <%= t :added_packages %>
        </a>
        <a href="<%= updated_packages_path %>" class="list-group-item">
          <span class="fa fa-fw fa-asterisk"></span>
          <%= t :updated_packages %>
        </a>
        <a href="<%= stable_packages_path %>" class="list-group-item">
          <span class="fa fa-fw fa-check-circle-o"></span>
          <%= t :stable_packages %>
        </a>
        <a href="<%= keyworded_packages_path %>" class="list-group-item">
          <span class="fa fa-fw fa-circle-o"></span>
          <%= t :keyworded_packages %>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<%= render partial: 'category_header', object: @category, as: 'category' %>

<div class="row">
  <div class="col-md-9">
    <!--<p>
      <input type="text" class="form-control form-control-xl" placeholder="Search packages in <%= @category.name %>">
    </p>-->

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">All packages</h3>
      </div>
      <table class="table">
        <%= render partial: 'package_line', collection: @packages, as: 'package' %>
      </table>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Statistics</h3>
      </div>
      <div class="panel-body">
        <%= @packages.count %> <%= t :packages %>
      </div>
    </div>
  </div>
</div>