config/routes.rb
Rails.application.routes.draw do
  get 'about/feedback'
  post 'about/feedback'
  get 'about', to: 'about#index'
  get 'about/feeds'
  get 'about/help'
  get 'about/changelog'

  root 'index#index'

  # Catch all old pgo feeds
  get 'feed(/*stuff)', to: 'about#legacy', defaults: { format: 'atom' }

  resources :categories, only: %i[index show search]

  resources :packages, only: [:index, :show, :search], constraints: { id: /[^.]*/ } do
    collection do
      get 'search'
      get 'suggest'
      get 'resolve'

      get 'added'
      get 'updated'
      get 'stable'
      get 'keyworded'
    end

    member do
      get 'changelog'
    end
  end

  resources :useflags do
    collection do
      get 'popular'
      get 'search'
      get 'suggest'
    end
  end

  resources :arches do
    member do
      get 'stable'
      get 'keyworded'
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/controllers/arches_controller.rb
class ArchesController < ApplicationController
  before_action :set_nav
  before_action :set_arch, only: [:show, :added, :updated, :stable, :keyworded]

  def index
  end

  def show
  end

  def stable
    @changes = stabled_packages @arch
    render_changes_feed :stable, t(:feed_stable_arch, arch: @arch)
  end

  def keyworded
    @changes = keyworded_packages @arch
    render_changes_feed :keyworded, t(:feed_keyworded, arch: @arch)
  end

  private

  def set_nav
    @nav = :arches
  end

  def set_arch
    fail ActionController::RoutingError, 'No such architecture' unless ::KKULEOMI_ARCHES.include? params[:id]
    @arch = params[:id]
    @feed_id = @arch
  end

  def render_changes_feed(type, title)
    respond_to do |wants|
      wants.html {}
      wants.atom do
        @feed_type = type
        @feed_title = title
        render template: 'feeds/changes'
      end
    end
  end

  def keyworded_packages(arch)
    Rails.cache.fetch("keyworded_packages/#{arch}", expires_in: 10.minutes) do
      Change.filter_all({ change_type: 'keyword', arches: arch },
                        size: 50,
                        sort: { created_at: { order: 'desc' } }).map do |change|
        change.to_os(:change_type, :package, :category, :version, :arches, :created_at)
      end
    end
  end

  def stabled_packages(arch)
    Rails.cache.fetch("stabled_packages/#{arch}", expires_in: 10.minutes) do
      Change.filter_all({ change_type: 'stable', arches: arch },
                        size: 50,
                        sort: { created_at: { order: 'desc' } }).map do |change|
        change.to_os(:change_type, :package, :category, :version, :arches, :created_at)
      end
    end
  end
end

app/helpers/arches_helper.rb
module ArchesHelper
end

app/views/arches/index.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li class="active"><%= t :architectures %></li>
</ol>

<h1><%= t :architectures %></h1>

<p><%= t :arches_intro %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t :architectures %></h3>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <col>
      <col style="width: 20em;">
      <col style="width: 20em;">
      <tbody>
      <% ::KKULEOMI_ARCHES.sort.each do |arch| %>
        <tr>
          <th class="kk-nobreak-cell"><%= arch %></th>
          <td>
            <%= link_to t(:keyworded_packages), keyworded_arch_path(id: arch) %>
            <%= feed_icon keyworded_arch_path(id: arch, format: :atom) %>
          </td>
          <td>
            <%= link_to t(:stable_packages), stable_arch_path(id: arch) %>
            <%= feed_icon stable_arch_path(id: arch, format: :atom) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/arches/keyworded.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to t(:architectures), arches_path %></li>
  <li class="active"><%= t :keyworded_packages %></li>
</ol>

<h1>
  <%= t :keyworded_packages %> (<%= @arch %>)
  <%= feed_icon keyworded_arch_path(id: @arch, format: :atom) %>
</h1>

<% cache("keyworded-full-#{@arch}-#{@changes.hash}") do %>
  <ul class="list-group">
    <% @changes.each do |change|
         _package = Package.find_by(:atom, cp_to_atom(change.category, change.package)) %>
      <%= render partial: 'packages/changed_package', object: change, as: 'change', locals: { package: _package, version: _package.version(change.version) } %>
    <% end %>
  </ul>
<% end %>

<% content_for :head do %>
  <%= alternate_feed_link(keyworded_arch_url(id: @arch, format: :atom), t(:atom_feed)) %>
<% end %>

app/views/arches/stable.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><%= link_to t(:architectures), arches_path %></li>
  <li class="active"><%= t :stable_packages %></li>
</ol>

<h1>
  <%= t :stable_packages %> (<%= @arch %>)
  <%= feed_icon stable_arch_path(id: @arch, format: :atom) %>
</h1>

<% cache("stable-full-#{@arch}-#{@changes.hash}") do %>
  <ul class="list-group">
    <% @changes.each do |change|
         _package = Package.find_by(:atom, cp_to_atom(change.category, change.package)) %>
      <%= render partial: 'packages/changed_package', object: change, as: 'change', locals: { package: _package, version: _package.version(change.version) } %>
    <% end %>
  </ul>
<% end %>

<% content_for :head do %>
  <%= alternate_feed_link(stable_arch_url(id: @arch, format: :atom), t(:atom_feed)) %>
<% end %>